In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

import warnings
warnings.filterwarnings('ignore')

# Load Dataset

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

# Train/Test Split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

# Scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[-0.60288866,  0.33589153, -0.56230009, ...,  0.02239354,
        -0.69529631,  0.90153517],
       [ 1.57893488,  0.44950992,  1.57040901, ...,  1.98784875,
         1.21258817,  0.22117452],
       [-0.12429511, -0.86057967, -0.17323308, ..., -0.33647546,
        -0.58727149, -1.02939844],
       ...,
       [-1.65044548,  0.32197907, -1.56871951, ..., -0.54350341,
         0.72896937,  3.61574578],
       [-0.72112941, -1.01593543, -0.72594553, ..., -0.27697227,
        -0.36457417, -0.30675864],
       [ 0.09529487, -0.64261786,  0.10373682, ...,  0.42165071,
         0.28191281,  0.22451235]])

In [9]:
y_train

286    B
2      M
240    B
275    B
67     B
      ..
13     M
47     M
151    B
249    B
340    B
Name: diagnosis, Length: 455, dtype: object

# Label Encoding

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,

# Numpy arrays to PyTorch tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [13]:
X_train_tensor.shape

torch.Size([455, 30])

In [14]:
y_train_tensor.shape

torch.Size([455])

In [15]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):

    def __init__(self, features, labels):
        self.features = features
        self.labels = labels
    
    def __len__(self):
        return len(self.features)
    
    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]


In [16]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [17]:
train_dataset[10]

(tensor([-1.3274e-01,  1.3144e+00, -1.4582e-01, -1.9408e-01, -9.3706e-02,
         -3.4912e-01, -3.6180e-03, -8.8160e-02, -7.2459e-01, -5.6889e-01,
          1.7935e-01,  1.0819e-01,  1.0282e-03,  5.5743e-02, -4.0359e-01,
         -5.8548e-01, -1.7033e-01, -3.1852e-01, -7.3813e-01, -5.3875e-01,
          1.5793e-01,  1.5524e+00,  5.4276e-02,  4.9886e-02, -2.5308e-01,
         -3.6411e-01,  2.6558e-01,  6.7098e-02, -3.8618e-01, -5.3596e-01]),
 tensor(1.))

In [18]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

# Defining the Model

In [19]:
import torch.nn as nn

class MySimpleNN(nn.Module):
    
    def __init__(self, num_features):

        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out


# Parameters

In [20]:
learning_rate = 0.1
epochs = 25

# Define Loss Function

In [21]:
loss_function = nn.BCELoss()

# Training Pipeline

In [22]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss function
loss_function = nn.BCELoss()

In [23]:
# define loop
for epoch in range(epochs):
    for batch_features, batch_labels in train_loader:
    
        # forward pass
        y_pred = model(batch_features)
    
        # loss calculate
        loss = loss_function(y_pred, batch_labels.view(-1,1))
        
        # clear gradients
        optimizer.zero_grad()
        
        # backward pass
        loss.backward()
        
        # parameters update
        optimizer.step()
    
    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')


Epoch: 1, Loss: 0.2748742699623108
Epoch: 2, Loss: 0.07522451877593994
Epoch: 3, Loss: 0.1826532632112503
Epoch: 4, Loss: 0.05320221185684204
Epoch: 5, Loss: 0.07159090042114258
Epoch: 6, Loss: 0.012505413964390755
Epoch: 7, Loss: 0.05339616537094116
Epoch: 8, Loss: 0.11078161746263504
Epoch: 9, Loss: 0.0861036628484726
Epoch: 10, Loss: 0.008790713734924793
Epoch: 11, Loss: 0.05135688930749893
Epoch: 12, Loss: 0.13672563433647156
Epoch: 13, Loss: 0.09783688932657242
Epoch: 14, Loss: 0.08733133971691132
Epoch: 15, Loss: 0.09583084285259247
Epoch: 16, Loss: 0.07086137682199478
Epoch: 17, Loss: 0.012810085900127888
Epoch: 18, Loss: 0.07132032513618469
Epoch: 19, Loss: 0.03251807764172554
Epoch: 20, Loss: 0.01913049817085266
Epoch: 21, Loss: 0.10902620851993561
Epoch: 22, Loss: 0.05200003832578659
Epoch: 23, Loss: 0.0021412153728306293
Epoch: 24, Loss: 0.30233076214790344
Epoch: 25, Loss: 0.009705634787678719


In [24]:
model.linear.weight

Parameter containing:
tensor([[ 0.5808,  0.5513,  0.4361,  0.4618,  0.1401,  0.1066,  0.4130,  0.5652,
          0.1992, -0.2937,  0.6511, -0.2114,  0.5315,  0.4685,  0.1465, -0.1981,
         -0.1140,  0.0520, -0.1519, -0.2561,  0.4984,  0.7379,  0.8173,  0.7236,
          0.4508,  0.1811,  0.4687,  0.6345,  0.5264,  0.1994]],
       requires_grad=True)

In [25]:
model.linear.bias

Parameter containing:
tensor([-0.5729], requires_grad=True)

# Model Evaluation using test_loader

In [26]:
model.eval()
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.9).float()  

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')


Accuracy: 0.9375
