In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

import warnings
warnings.filterwarnings('ignore')

# Load Dataset

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

# Train/Test Split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

# Scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[-0.62626714,  2.02017476, -0.65488688, ..., -0.91671388,
        -0.78027118, -0.94911327],
       [-0.54377658, -1.59635506, -0.56944313, ..., -0.31157992,
        -0.09723269, -0.87601252],
       [ 0.56100766,  0.07069297,  0.50928416, ...,  0.60289022,
        -0.38304312, -1.08866924],
       ...,
       [ 0.64349821,  0.90651319,  0.71862134, ...,  1.74892957,
         3.12741952,  0.6984225 ],
       [ 0.59046857, -0.75135   ,  0.60327229, ...,  0.17942238,
         0.42917524,  0.33624153],
       [-0.8089248 ,  0.23831626, -0.62369991, ...,  2.26370274,
         6.0565728 ,  4.95487962]])

In [9]:
y_train

471    B
170    B
75     M
173    B
344    B
      ..
551    B
100    M
370    M
375    B
3      M
Name: diagnosis, Length: 455, dtype: object

# Label Encoding

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,

# Numpy arrays to PyTorch tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [13]:
X_train_tensor.shape

torch.Size([455, 30])

In [14]:
y_train_tensor.shape

torch.Size([455])

# Defining the Model

In [15]:
import torch.nn as nn

class MySimpleNN(nn.Module):
    
    def __init__(self, num_features):

        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out


# Parameters

In [16]:
learning_rate = 0.1
epochs = 25

# Define Loss Function

In [17]:
loss_function = nn.BCELoss()

# Training Pipeline

In [18]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(epochs):

    # forward pass
    y_pred = model(X_train_tensor)
    
    # loss calculate
    loss = loss_function(y_pred, y_train_tensor.view(-1,1))
    
    # clear gradients
    optimizer.zero_grad()
    
    # backward pass
    loss.backward()
    
    # parameters update
    optimizer.step()
    
    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7385793924331665
Epoch: 2, Loss: 0.5587444305419922
Epoch: 3, Loss: 0.46481356024742126
Epoch: 4, Loss: 0.4065243899822235
Epoch: 5, Loss: 0.36616969108581543
Epoch: 6, Loss: 0.3362485468387604
Epoch: 7, Loss: 0.3129909634590149
Epoch: 8, Loss: 0.2942770719528198
Epoch: 9, Loss: 0.2788165211677551
Epoch: 10, Loss: 0.26577556133270264
Epoch: 11, Loss: 0.2545897960662842
Epoch: 12, Loss: 0.24486234784126282
Epoch: 13, Loss: 0.23630531132221222
Epoch: 14, Loss: 0.2287043035030365
Epoch: 15, Loss: 0.2218959927558899
Epoch: 16, Loss: 0.21575365960597992
Epoch: 17, Loss: 0.2101771980524063
Epoch: 18, Loss: 0.20508639514446259
Epoch: 19, Loss: 0.20041611790657043
Epoch: 20, Loss: 0.19611278176307678
Epoch: 21, Loss: 0.19213208556175232
Epoch: 22, Loss: 0.18843668699264526
Epoch: 23, Loss: 0.18499517440795898
Epoch: 24, Loss: 0.18178066611289978
Epoch: 25, Loss: 0.17877012491226196


In [21]:
model.linear.weight

Parameter containing:
tensor([[ 0.2513,  0.1741,  0.2796,  0.2588,  0.1923,  0.1878,  0.2121,  0.2113,
          0.1203, -0.1417,  0.3506,  0.0867,  0.0038,  0.0188,  0.0089, -0.0554,
          0.0314, -0.0040,  0.0078,  0.0054,  0.1366,  0.2093,  0.4331,  0.3976,
          0.1121,  0.2797,  0.1235,  0.1124,  0.1535,  0.0562]],
       requires_grad=True)

In [22]:
model.linear.bias

Parameter containing:
tensor([-0.0649], requires_grad=True)

# Model Evaluation

In [20]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5538627505302429
